component: frontend
service:
  port: 80
  containerPort: 80

initContainers:
  parameters_pull:
    image: docker.io/rkalluru/d77-parameter-store-init-container-image
    imagePullPolicy: Always

containers:
  main:
    image: rkalluru/d77-frontend
    imagePullPolicy: Always



